name: Create new release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build phar file
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: curl, mbstring, json

    - name: Build
      run: |
          php --define phar.readonly=0 create-phar.php

    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bb.phar
        asset_name: bb
        tag: ${{ github.ref }}
        release_name: "Release ${{ github.ref }}"
        overwrite: true
