name: build-phar-file

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build phar file
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.1'
        run: |
          php --define phar.readonly=0 create-phar.php # creates bb.phar file
          ls -lah
      
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bb.phar
        asset_name: bb.phar
        tag: ${{ github.ref }}
        overwrite: true
        body: "Release"
