name: build-phar-file

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run composer install
      uses: baschny/php-composer-action@v1
      with:
        composer_version: 2
        command: build
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bb.phar
        asset_name: bb
        tag: ${{ github.ref }}
        overwrite: true
        body: "Release"
